name: Build, Push & Deploy Landing App

on:
  push:
    branches:
      - main
      - 'v*.*.*' # Match version tags like v1.0.0, v2.3.4, etc.
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app (standalone)
        run: yarn build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          target: runner

  deploy:
    name: Deploy to VPS via SSH
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      WORKDIR: projects/${{ github.repository }}

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ env.WORKDIR }} && cd ${{ env.WORKDIR }}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose pull
            docker compose up -d --remove-orphans