name: Build and Release Landing

on:
  push:
    tags:
      - "v*.*.*" # Only run when a version tag is pushed
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          target: runner

      - name: Trigger deploy tag in lnfoot-infra-deploy  
        env:  
          DEPLOY_REPO: hublot-tech/lnfoot-infra-deploy  
          VERSION_TAG: admin-${{ github.ref_name }}  
        run: |  
          # Retrieve the SHA of the main branch  
          MAIN_SHA=$(git ls-remote https://github.com/${{ env.DEPLOY_REPO }} refs/heads/main | cut -f1)  
          # Create the tag  
          curl -X POST \  
            -H "Authorization: token ${{ secrets.INFRA_DEPLOY_TOKEN }}" \  
            -H "Accept: application/vnd.github.v3+json" \  
            https://api.github.com/repos/${{ env.DEPLOY_REPO }}/git/refs \  
            -d "$(jq -nc \  
                  --arg ref "refs/tags/${{ env.VERSION_TAG }}" \  
                  --arg sha "$MAIN_SHA" \  
                  '{ref: $ref, sha: $sha}')"  